name: fluttersocial
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  firebase_storage: ^11.0.2
  image_picker: 0.8.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets_all/
    - assets_all/assets /darkBee.png
    - assets_all/assets /event.jpg
  uses-material-design: true

